### ISSUE TITLE
Automatically select a user's password if it exists

### ISSUE THREAD

**Issue by untuned** [SammCheese/invisible-chat#1]
If I open the prompt to send a secret message, I would like for it to automatically choose the option for that user, if I have added them to the plugin settings.

**Comment by SammCheese** [comment]
Could you further explain what you mean?

From what i can take is that if you try to decrypt a users message that you added in the Plugin settings, it should Automatically select the password for that user

**Comment by untuned** [comment]
> Could you further explain what you mean?
> 
> From what i can take is that if you try to decrypt a users message that you added in the Plugin settings, it should Automatically select the password for that user

Yes, that's exactly what I would like to see (along with encrypting, if you're in their DMs).

I have added a friend to the users list, as shown in the following screenshot:
![in-settings](https://untnd.me/DV1wb4QLG)

It doesn't show their avatar in the "box" next to their name (made https://github.com/SammCheese/invisible-chat/issues/3), and when trying to encrypt or decrypt a message in their DM, it does not automatically select. That's what I would like to do.

**Comment by SammCheese** [comment]
Alright, ill look into this!

**Comment by SammCheese** [comment]
It should be somewhat working now, if you encounter issues, please open a new Issue
