### ISSUE TITLE
Clean install, doesnt seem to work

### ISSUE THREAD

**Issue by SheepCommander** [SammCheese/invisible-chat#10]
![image](https://user-images.githubusercontent.com/66646514/149247910-f205fb4b-b492-4588-95d7-6711940e3f2b.png)
![image](https://user-images.githubusercontent.com/66646514/149247966-2ad74d34-b84f-43df-98e6-d90ed27b0ade.png)

**Comment by SheepCommander** [comment]
`.invichat` also broken

![image](https://user-images.githubusercontent.com/66646514/149248015-b1696035-cf2b-4112-aa4f-c9502eeec09f.png)
![image](https://user-images.githubusercontent.com/66646514/149248028-d06ab05b-9ef7-4eeb-8269-ff9721d501d6.png)

**Comment by SammCheese** [comment]
.invichat is up for deprecation and will be reworked soon anyway

**Comment by SheepCommander** [comment]
Aight

**Comment by SammCheese** [comment]
Rewrite should fix those issues
