### ISSUE TITLE
password suggestion

### ISSUE THREAD

**Issue by DRB02** [SammCheese/invisible-chat#13]
Sometimes I just want to send a message for only the people in the server who use powercord.
But if I post a message, they just need to guess which password I will use. Some people use a space as a standard password, others use "password".

It would be nice to have a standard password set. Anyone can change the password if they want to, but you will never have to guess which is the standard password for people. 

That would be nice to have. 
Thank you for your hard work! :)

**Comment by SammCheese** [comment]
Done, "password" should now be in the password field by default
