### ISSUE TITLE
Suggestion: Move the Create Hidden Message button to the upload menu

### ISSUE THREAD

**Issue by RuinTD** [SammCheese/invisible-chat#14]
It would be nice if the Create Hidden Message button was instead in the Upload File menu, out of the way until it's needed, similar to the [Tone Indicators plugin](https://github.com/asportnoy/powercord-tone-indicators):
![](https://files.catbox.moe/lobu5g.png)

**Comment by SammCheese** [comment]
Done :trollface:

**Comment by RuinTD** [comment]
...that emoji slightly concerns me, but thanks.

**Comment by SammCheese** [comment]
No Need to be concerned :smiley:
