### ISSUE TITLE
Can't decode.

### ISSUE THREAD

**Issue by uhlow** [SammCheese/invisible-chat#16]
![Screenshot_4](https://user-images.githubusercontent.com/124531614/216845912-57099dc4-63c0-406d-a642-3c7f64dea1dc.png)

**Comment by SammCheese** [comment]
could you copy-paste the message here?

**Comment by uhlow** [comment]
example ‌⁤⁢‌‍⁢‌⁢‌‍‌⁢⁣‍‌⁤⁡⁤⁤⁢‌⁢⁡⁤‍‌⁡⁢⁢⁡⁢⁣‍⁣⁢⁡‌‍⁣⁡‌⁢⁡‌⁡⁡⁤‌‍‌⁡⁤⁡⁡‌‍‌⁡⁢⁡⁡‍‌code

**Comment by SammCheese** [comment]
Thank you for the Issue report! Discord happened to change the Minipopover code, which is why the button didnt appear.
I adjusted the patch and it should work just fine now :D

**Comment by uhlow** [comment]
I noticed 2/3days ago, and i was like weird shit going on and then ye why not report the bug.

**Comment by uhlow** [comment]
Btw i was checking and its not working for me yet. :D

**Comment by SammCheese** [comment]
you gotta update the plugin

**Comment by uhlow** [comment]
xdd yeyee and i was doing some weird shit
