### ISSUE TITLE
no decrypt message button

### ISSUE THREAD

**Issue by WlodekM** [SammCheese/invisible-chat#17]
![image](https://user-images.githubusercontent.com/75479945/228793704-e9d1c4c7-6bf2-4b0d-a80a-f6f83d68ee81.png)
(The password was password)

**Comment by SammCheese** [comment]
This could be one of 2 things. Either the message doesnt match the encryption Regex (which can happen sometimes) or the issue is on Repluggeds Minipopover API which i have no control over.

**Comment by SammCheese** [comment]
Mind telling me what version of replugged you are on?

**Comment by SammCheese** [comment]
This appears to be caused by an outdated Vencord version. Please update Vencord and everything should work again.
