### ISSUE TITLE
how do you decrypt the message

### ISSUE THREAD

**Issue by ghost** [SammCheese/invisible-chat#18]
i watched the gif on the github but i cant find that button anywhere

**Comment by SammCheese** [comment]
cant reproduce on canary, need more info

**Comment by SammCheese** [comment]
Mind telling me on what version of replugged you are on?

**Comment by ghost** [comment]
it seems to be broken on vencord if that's what you're using

**Comment by SammCheese** [comment]
It seems to work just fine on vencord?
Are you perhaps using the version of the plugin that was posted in Vencords third-party-plugins channel?

**Comment by ghost** [comment]
nope I was using the version that was in the plugins list  but using replugged seemed to fix it

**Comment by SammCheese** [comment]
odd, i just did some testing on vencord and it seemed to work on stable

**Comment by ghost** [comment]
hmmmm... I was using win 11 latest version of both vencord and discord, tested it on canary and stable. Wanted to try it on linux but couldn't be bothered could that by any chance be the case?

**Comment by SammCheese** [comment]
This appears to be caused by an outdated Vencord version. Please update Vencord and everything should work again.
