### ISSUE TITLE
decryption button doesnt work.

### ISSUE THREAD

**Issue by sskeyog** [SammCheese/invisible-chat#25]
Hello!  I have updated vencord and 
![image](https://github.com/user-attachments/assets/93542434-2235-4acd-9e4b-09ee1dcddd7c)
this button doesnt works when i press it. But encryption button works. is there any solution?

**Comment by SammCheese** [comment]
Invisible Chat is a part of the official Vencord Desktop version "Vesktop", the party party plugin from this github is not really supported anymore

**Comment by sskeyog** [comment]
oh, thats sad

**Comment by sskeyog** [comment]
oh, thats sad
