### ISSUE TITLE
Lock dosent appear in chatbar ‌‌‍​​⁠‌‍​

### ISSUE THREAD

**Issue by sekkedev** [SammCheese/invisible-chat#4]
Im still able to decrypt messages but I cant make them the lock doesn't appear in the chat bar. screenshot- https://anime.thigh-highs.store/​‌‌‍​​⁠‌‍​⁠‍‌​​‌‍⁠‌‌​‌⁠​‍​

**Comment by sekkedev** [comment]
![image](https://user-images.githubusercontent.com/68520534/126883927-0497a821-422f-4af5-a96e-382d251e387c.png)

**Comment by SammCheese** [comment]
Hmm, thats odd. Could you provide the console errors?

**Comment by sekkedev** [comment]
Im new to powercord and discord canary how do I do that?

**Comment by sekkedev** [comment]
`VM158 C:\Users\sekke\powercord\src\fake_node_modules\powercord\entities\Plugin.js:107 [Powercord:Plugin:InviChat] An error occurred during initialization! TypeError: Cannot read property 'type' of null
    at InviChat.injectIcon (VM1179 C:\Users\sekke\powercord\src\Powercord\plugins\invisible-chat\index.js:131)
    at InviChat.startPlugin (VM1179 C:\Users\sekke\powercord\src\Powercord\plugins\invisible-chat\index.js:224)
    at async InviChat._load (VM158 C:\Users\sekke\powercord\src\fake_node_modules\powercord\entities\Plugin.js:127)`

**Comment by sekkedev** [comment]
the only error containing invichat

**Comment by SammCheese** [comment]
There shouldnt be an error, could you try to delete the plugin and reinstall it?

**Comment by sekkedev** [comment]
Already did

**Comment by SammCheese** [comment]
Hmm odd...
I cant really reproduce it. `ChannelTextAreaContainer.type` should always exist

**Comment by sekkedev** [comment]
Ill check if i have a different plugin witch might mess with it

**Comment by sekkedev** [comment]
Yes i fixed it. i disabled a channel locker plugin and it works now

**Comment by SammCheese** [comment]
Alright, Closing Issue
