### ISSUE TITLE
Tryin to click the lock completely kills powercord

### ISSUE THREAD

**Issue by cKnei** [SammCheese/invisible-chat#5]
So I tested it out and sending a encrypted message with password. Attempting to click the lock crashes discord completely. ( File that error originated from invisible-chat\components\ModalComposerDecrypt.jsx:85 )

**Comment by SammCheese** [comment]
Ah fuck didnt calcule that in, ill try to fix it asap

**Comment by SammCheese** [comment]
Hopefully fixed this issue, if you still experience some, please tell me
