### ISSUE TITLE
Tryin to click the lock completely kills powercord

### ISSUE THREAD

**Issue by erxson** [SammCheese/invisible-chat#6]

**Comment by erxson** [comment]
log?

<html>
<body>
<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">264339f<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.js:135</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read property 'settings' of undefined
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ModalComposer.render (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">VM1627 D:\powercord\<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>poserEncrypt.jsx:53</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | (anonymous) | @ | 264339f….js:135
-- | -- | -- | --
  | cs | @ | 989316a….js:4045
  | o.componentDidCatch.n.callback | @ | 989316a….js:4045
  | lo | @ | 989316a….js:4005
  | ms | @ | 989316a….js:4047
  | Mu | @ | 989316a….js:4065
  | t.unstable_runWithPriority | @ | 989316a….js:4086
  | Hi | @ | 989316a….js:4002
  | Pu | @ | 989316a….js:4061
  | mu | @ | 989316a….js:4057
  | (anonymous) | @ | 989316a….js:4002
  | t.unstable_runWithPriority | @ | 989316a….js:4086
  | Hi | @ | 989316a….js:4002
  | ji | @ | 989316a….js:4002
  | Yi | @ | 989316a….js:4002
  | Me | @ | 989316a….js:4079
  | Zt | @ | 989316a….js:3979
  | listener | @ | VM94:35

</span></div>
</body>
</html>

**Comment by SammCheese** [comment]
I cant replicate this, could you give me more details?

When exactly does it happen?
Did you add passwords in invisible-chats settings before?

**Comment by erxson** [comment]
no. It happens when i click on gui button

ср, 25 авг. 2021 г. в 18:54, Samm-Cheese ***@***.***>:

**Comment by SammCheese** [comment]
I cant really find an issue with it, perhaps try to completely reinstall it or add a test user in settings
