### ISSUE TITLE
props.replyError is not a function

### ISSUE THREAD

**Issue by Wolfhound905** [SammCheese/invisible-chat#7]
![image](https://user-images.githubusercontent.com/58155937/141030896-d9a6dd6e-1128-42c7-b82d-1cb07bd2703b.png)

**Comment by SammCheese** [comment]
when did this error happen?

**Comment by Wolfhound905** [comment]
When trying to use the command or hide a message.

**Comment by SammCheese** [comment]
i cant really reproduce it, could you screenshot the error from your console?

**Comment by Wolfhound905** [comment]
I just reinstalled windows so I will let you know how it goes.

**Comment by Wolfhound905** [comment]
@SammCheese sorry bout that, seems there was a problem in one of my installs. I can not reproduce this anymore.

**Comment by SammCheese** [comment]
Alright, Glad you're not experiencing that issue anymore
