### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Armaan-Raisinghani** [SammCheese/invisible-chat#8]
TypeError: Object.defineProperties called on non-object
    at Function.defineProperties (<anonymous>)

**Comment by SammCheese** [comment]
Any more infos about this?

**Comment by SammCheese** [comment]
Right, ill close this issue in 2 days unless more info is given, you can also try to reinstall the plugin and see if that fixes your issue.

**Comment by SammCheese** [comment]
Closing.
